# .github/workflows/workflows/prueba.yml
name: PRUEBA EXITOSA DE ACTIONSFLOW
on:
  # Dejamos el cron de 1 minuto para que se ejecute solo si fallamos el manual
  schedule:
    - cron: "* * * * *" 
  
jobs:
  job_de_prueba:
    name: Generar Resultado
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Mensaje de confirmacion
        run: |
          echo "========================================="
          echo "¡ACTIONSFLOW ESTÁ LISTO PARA AUTOMATIZAR!"
          echo "========================================="
          
      # ⚠️ SOLO VAMOS A CREAR EL ARCHIVO, NO HACER COMMIT
      - name: Crear archivo de confirmacion
        run: |
          DATE=$(date +'%Y-%m-%d_%H:%M:%S')
          echo "Prueba exitosa ejecutada el: $DATE" > prueba_de_trabajo_solo_creacion.txt
          
      # ELIMINAMOS EL PASO Commit y Subida de Archivo
