name: Actionsflow
on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:
    inputs:
      include:
        description: "Filter your workflows (glob format)"
        required: false
        default: ""
      force:
        description: "Force to run workflow, true or false"
        required: false
        default: "false"
      verbose:
        description: "Debug workflow, true or false"
        required: false
        default: "false"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    concurrency: actionsflow
    steps:
      - uses: actions/checkout@v3
      - name: Run Actionsflow 
        uses: actionsflow/actionsflow-action@v1.3.0
        with:
          # CAMBIAR a "run" para que compile Y ejecute
          args: "run --include ${{ github.event.inputs.include || ''}} -f ${{github.event.inputs.force=='true' && 'true' || 'false'}} --verbose ${{github.event.inputs.verbose=='true' && 'true' || 'false'}}"
          json-secrets: ${{ toJSON(secrets) }}
          json-github: ${{ toJSON(github) }}
      # ELIMINAR LOS PASOS "Setup act" y "Run act" DE AQUÍ EN ADELANTE
