# .github/workflows/contador_diario.yml

name: Contador Diario y Confirmación

on:
  # AÑADIR ESTA SECCIÓN: Se dispara con cada commit a la rama 'main'
  push:
    branches: [ main ] # Asumiendo que tu rama principal es 'main'
  # 1. Disparo Manual (para la primera prueba)
  workflow_dispatch:
  # 2. Disparo Programado: Se ejecuta cada hora (0 minutos de cada hora)
  schedule:
    - cron: '0 * * * *' 

# Permisos CRÍTICOS: el token necesita permiso para escribir en el repositorio
permissions:
  contents: write

jobs:
  actualizar_contador:
    name: Crear y Actualizar Archivo
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Descargar el código actual
      - name: Checkout del Repositorio
        uses: actions/checkout@v4
        with:
          # Es necesario pasar el token al checkout para la acción de push
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      # Paso 2: Generar el contenido del archivo
      - name: Generar Contenido y Fecha
        id: generate
        run: |
          FECHA_ACTUAL=$(date +'%Y-%m-%d %H:%M:%S')
          echo "La última ejecución exitosa fue el: $FECHA_ACTUAL" > AUTOMATIZACION_EXITOSA.txt
          
     # Paso 3: Realizar el commit del nuevo archivo/cambio
      - name: Commit y Subida de Archivo (Final)
        # Usamos la acción estable de auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Define los archivos que deben ser agregados/subidos
          commit_message: 'AUTOMATIZACION: Contador diario actualizado [CORRECCIÓN FINAL]'
          # La siguiente línea indica que debe agregar TODOS los archivos modificados
          file_pattern: 'AUTOMATIZACION_EXITOSA.txt'
          # Usamos el token nativo que ya tiene permisos de escritura
          token: ${{ secrets.GITHUB_TOKEN }}
